---
- name: "deploy backend"
  become_user: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "run backend"
  become_user: true
  shell: |
    cd ~/
    npm install
    pm2 stop default
    pm2 start npm -- run start
