---
- name: "deploy backend"
  become_user: true
  unarchive:
    src: /zip/artifact.tar.gz
    dest: ~/udapeople-backend

- name: "run backend"
  become_user: true
  shell: |
    cd ~/udapeople-backend
    npm i
    pm2 start npm -- run start
