#!/bin/bash
# bucket=$(aws s3api list-buckets --query "Buckets[].Name" --profile Admin --output text | sed 's/udapeople-//g' | sed 's/hh33h//g')


# for VARIABLE in 0e790eb 3db5619 ab41e80 bbb6996 d47ae61 da69f09
for VARIABLE in $(aws s3api list-buckets --query "Buckets[].Name" --profile Admin --output text | sed 's/udapeople-//g' | sed 's/hh33h//g')
do
    aws s3 rm s3://udapeople-$VARIABLE --recursive --profile Admin --region us-east-1
    aws cloudformation delete-stack --stack-name udapeople-frontend-$VARIABLE --profile Admin  --region us-east-1
    aws cloudformation delete-stack --stack-name udapeople-backend-$VARIABLE --profile Admin  --region us-east-1
done